uploads = []
outputs = []

[[generated]]
id = "CGKzGbDAYtQPdHY2xus_A"
uri = "file://artifacts/api-server/public/assets/images/great-ideas-card.png"
type = "image"
title = "goofy seagull scene square"

[[generated]]
id = "LNOOrDLKTOZjTFqCqtv2T"
uri = "file://artifacts/api-server/public/assets/images/cabin-essentials-card.png"
type = "image"
title = "cruise cabin clean square"

[[generated]]
id = "KB06vGMF_jCw5CV3-c-kp"
uri = "file://artifacts/api-server/public/assets/images/cruise-fun-card.png"
type = "image"
title = "cruise fun scene square"

[[generated]]
id = "hgwz506rYCCdmjxsaL7N_"
uri = "file://artifacts/api-server/public/assets/images/air-travel-card.png"
type = "image"
title = "air travel scene square"

[[generated]]
id = "L3r0aa2g0esLNCfJ4XGhv"
uri = "file://attached_assets/generated_images/the_text_stay_afloat_eca6.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fHoCClpOcIyJIi4x0AC_W"
uri = "file://artifacts/api-server/public/assets/images/still-afloat-text.png"
type = "image"
title = "generated_image"

[[generated]]
id = "jQb8Yr0K6fMI0h6NdXQ0n"
uri = "file://attached_assets/generated_images/text_logo_image_saying_1600.png"
type = "image"
title = "generated_image"

[[generated]]
id = "047CI4Boe_ipJ-jTQNaLi"
uri = "file://attached_assets/generated_images/stay-afloat-white-bg.png"
type = "image"
title = "generated_image"
