import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import socialRouter from "./social";
import newsletterRouter from "./newsletter";
import affiliateIngestRouter from "./affiliate-ingest";
import feedsRouter from "./feeds";
import newsArchiveRouter from "./news-archive";
import weatherRouter from "./weather";
import affiliateRouter from "./affiliate";
import favoritesRouter from "./favorites";
import commentaryRouter from "./commentary";
import translateArticleRouter from "./translate-article";
import subscribeRouter from "./subscribe";
import youtubeRouter from "./youtube";
import contactRouter from "./contact";
import opsFinanceRouter from "./ops-finance";
import opsGscRouter from "./ops-gsc";
import pushRouter from "./push";
import briefRouter from "./brief";
import stormRouter from "./storm";
import socialAnalyticsRouter from "./social-analytics";
import actionsRouter from "./actions";
import proposalsRouter from "./proposals";
import webcamsRouter from "./webcams";
import wmsRouter from "./wms";
import congaLineRouter from "./conga-line";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(socialRouter);
router.use(newsletterRouter);
router.use(affiliateIngestRouter);
router.use(feedsRouter);
router.use(newsArchiveRouter);
router.use(weatherRouter);
router.use(affiliateRouter);
router.use(favoritesRouter);
router.use(commentaryRouter);
router.use(translateArticleRouter);
router.use(subscribeRouter);
router.use(youtubeRouter);
router.use(contactRouter);
router.use(opsFinanceRouter);
router.use(opsGscRouter);
router.use(pushRouter);
router.use(briefRouter);
router.use(stormRouter);
router.use(socialAnalyticsRouter);
router.use(actionsRouter);
router.use(proposalsRouter);
router.use(webcamsRouter);
router.use(wmsRouter);
router.use(congaLineRouter);

export default router;
