kind = "api"
  previewPath = "/"
  title = "stillafloatcruising.com (preview)"
  version = "1.0.0"
  id = "3B4_FFSkEVBkAeYMFRJ2e"

  [[services]]
  localPort = 8080
  name = "API Server"
  paths = ["/"]

  [services.development]
  run = "pnpm --filter @workspace/api-server run dev"

  [services.production]

  [services.production.build]
  args = ["pnpm", "--filter", "@workspace/api-server", "run", "build:all"]

  [services.production.build.env]
  NODE_ENV = "production"
  PORT = "18336"
  BASE_PATH = "/dashboard/"
  VITE_API_BASE_URL = "https://stillafloatcruising.com"

  [services.production.run]
  args = ["node", "--enable-source-maps", "server/dist/index.mjs"]

  [services.production.run.env]
  PORT = "8080"
  NODE_ENV = "production"

  [services.production.health.startup]
  path = "/api/healthz"
