-- 0007_cabin_advisor.sql
-- Cabin Advisor ("Room Engine") data layer. Mirrors the two proven extraction
-- structures from the 2026-07-26/27 build:
--   • DeckMaps BASE GRID  — every stateroom: number, deck, geometry, category,
--     section, side (the complete, exhaustive ship inventory).
--   • Per-class MOAT LAYER — view quality, real-ocean vs interior-facing, hump,
--     steadiness, obstruction grade, sleeps, YouTube tour link (the differentiator;
--     filled in per hull class, so the columns are nullable on first load).
-- One row per ship in cabin_ships, one row per stateroom in cabins.
-- Isolated from the live site until explicitly wired. RLS service-role-only
-- (served via the backend, like sailings/ship_watches). Apply DEV FIRST, PROD
-- after sign-off.

CREATE TABLE IF NOT EXISTS public.cabin_ships (
  slug             text PRIMARY KEY,        -- e.g. 'wonder-of-the-seas'
  ship             text NOT NULL,
  line             text,
  class            text,                    -- hull class (build unit; sisters reuse)
  source           text,
  source_detail    text,
  svg_version      text,
  extracted_on     date,
  deck_count       integer,
  total_cabins     integer,
  decks            integer[],
  category_counts  jsonb,
  color_legend     jsonb,
  notes            jsonb,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cabins (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ship_slug       text NOT NULL REFERENCES public.cabin_ships(slug) ON DELETE CASCADE,
  cabin_num       text NOT NULL,
  deck            integer,
  category        text,
  section         text,          -- forward / mid / aft (geometric heuristic)
  side            text,          -- port / starboard (geometric; validate vs a known cabin)
  x               numeric,       -- DeckMaps raw geometry (provenance / future dedup)
  y               numeric,
  fill            text,          -- source fill colour → category mapping provenance
  obstructed      boolean NOT NULL DEFAULT false,
  -- moat layer (nullable; filled by the per-class research pass)
  view            text,
  real_ocean      boolean,
  hump            boolean,
  steady          boolean,
  obstruction     text,          -- grade: none / light / partial / heavy
  flagged_by_line boolean,
  sleeps          integer,
  tour            text,          -- YouTube video id for a cabin/category tour
  tier            integer,
  note            text,
  UNIQUE (ship_slug, cabin_num)
);

CREATE INDEX IF NOT EXISTS cabins_ship_idx      ON public.cabins (ship_slug);
CREATE INDEX IF NOT EXISTS cabins_ship_cat_idx  ON public.cabins (ship_slug, category);
CREATE INDEX IF NOT EXISTS cabins_ship_deck_idx ON public.cabins (ship_slug, deck);

ALTER TABLE public.cabin_ships ENABLE ROW LEVEL SECURITY; -- service-role only
ALTER TABLE public.cabins      ENABLE ROW LEVEL SECURITY; -- service-role only
